# Generated by Django 5.2.4 on 2025-07-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TO_DO_LIST',
        ),
    ]
