# Generated by Django 5.2.4 on 2025-07-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_todo_to_do_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='task',
            field=models.CharField(max_length=150),
        ),
    ]
